### ISSUE TITLE
ticket mod role error

### ISSUE THREAD

**Issue by ultra-beep** [Khanmanan/automod-bot#50]
hey when i setup the tickets it doesn't give the perms to the role that needs to manage the tickets can you help me with it

**Comment by heliodoros** [comment]
I can confirm this

**Comment by ThePigeonKings** [comment]
> hey when i setup the tickets it doesn't give the perms to the role that needs to manage the tickets can you help me with it

Do you get any errors?

**Comment by ultra-beep** [comment]
no 
just when i look at the ticket channel the perms aren't there

**Comment by ThePigeonKings** [comment]
> no just when i look at the ticket channel the perms aren't there

Alright, Im looking into how to fix it. But i might not be able to fix it.

**Comment by ultra-beep** [comment]
fixed it alr my self thx for your time tho

**Comment by heliodoros** [comment]
> fixed it alr my self thx for your time tho

how?
