### ISSUE TITLE
Spotify Music Not Working.

### ISSUE THREAD

**Issue by TheGamer3514** [Khanmanan/automod-bot#51]
Hi! So All The Music works however spotify links do not. does anyone know what files make it work? i changed some things and i cant work out which file is causing it

**Comment by ThePigeonKings** [comment]
Did you input the right Spotify Client ID and Secret?

**Comment by TheGamer3514** [comment]
yes

**Comment by TheGamer3514** [comment]
![image](https://user-images.githubusercontent.com/79448904/183830825-b917724b-e857-463b-aba0-ea081a9d0d4c.png)
this is the error shown in console

**Comment by TheGamer3514** [comment]
yes i did
