### ISSUE TITLE
Music config not clear/Music not working

### ISSUE THREAD

**Issue by gggdunlix** [Khanmanan/automod-bot#58]
So not sure what to put for this section of the config:
![image](https://user-images.githubusercontent.com/33298379/184559680-7e63353e-5188-4043-9974-79016039f590.png)

Also is fails to connect to these credentials:
![image](https://user-images.githubusercontent.com/33298379/184559704-48d832a1-b919-4528-a724-a1ab8b1cdf45.png)

And this happens when using /play:
![image](https://user-images.githubusercontent.com/33298379/184559738-9a14bd29-de80-4c50-9408-00289f132a7c.png)

Any ideas or just clarification on how to use the music config?

**Comment by luna-morningstar** [comment]
You need to change the lavalink node to one that is working and accepting connections. Here is a site with a list of public ones.
https://lavalink-list.darrennathanael.com/
You can also host a node yourself using Java. Here's a link to a tutorial on how to do that.
https://darrennathanael.com/post/how-to-lavalink?utm_source=lavalink-list&utm_medium=home&utm_campaign=mainmd

**Comment by gggdunlix** [comment]
> You need to change the lavalink node to one that is working and accepting connections. Here is a site with a list of public ones. https://lavalink-list.darrennathanael.com/ You can also host a node yourself using Java. Here's a link to a tutorial on how to do that. https://darrennathanael.com/post/how-to-lavalink?utm_source=lavalink-list&utm_medium=home&utm_campaign=mainmd

Thank you so much for responding!

None of the hosts I tried worked, so I decided to local host it and it works! thanks! Also hopes this helps someone else
