### ISSUE TITLE
Bot wont start 

### ISSUE THREAD

**Issue by flexhd41** [Khanmanan/automod-bot#63]
so it cant connect to something 
![image](https://user-images.githubusercontent.com/83534174/189714619-0b68c976-0875-4cc8-aafd-f5b763de4d8d.png)

**Comment by flexhd41** [comment]
is there a way to deactivate music

**Comment by flexhd41** [comment]
oh fixed 
it smh

**Comment by PC1up** [comment]
how did you fix it? im experiencing exactly the same issue with the same ip address
