### ISSUE TITLE
Dashboard Selector issue (dashboard form)

### ISSUE THREAD

**Issue by alidexter001** [Khanmanan/automod-bot#67]
hi i got a problem with the dashboard form, it's not showing up like it have to be:
![image](https://user-images.githubusercontent.com/53831484/191815954-88f128d1-dce5-4717-a92b-e2e9c0bf3655.png)

sometimes it's show this message error too and make the bot shutdown:
TypeError: Cannot read properties of null (reading 'id')
    at /home/runner/automod-bot/dashboard/routes/discord.js:12:25

**Comment by ShadowMethods** [comment]
You dont have the files right dm me on discord ill help ShadowR#0001

**Comment by alidexter001** [comment]
@ShadowMethods i sended you friend request my name is: !S̷p̷o̷o̷k̷y̷C̷4#7137

**Comment by Sheepgaming1** [comment]
@ShadowMethods added you on discord

**Comment by Sheepgaming1** [comment]
how did you get your dashboard to work @ShadowMethods as i cant get past the issue raised in #60

**Comment by alidexter001** [comment]
@Sheepgaming1 there is the new dashboard on the Cw/khan discord server you can go and copy it
